image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo 'Preparing environment'
    command: |
      echo 'Activating conda environment'
      source /home/gitpod/miniconda/bin/activate dcgan_env
      echo 'Environment is ready!'
